export var AbsLogo="/assets/abministrylogo.png"
export var ABSTabletBanner="/assets/ABS_banner-tablet.png"
export var ABSDesktopBanner="/assets/ABMinistriesHero.png"
export var LoadingIcon="/assets/loading.png"
export var AboutGif="/assets/about.gif"
export var ABMVideo="/assets/AntiBlasphemyMinistriesSplash.mp4"
