export var AbsLogo="/assets/ABSLogo.png"
export var ABSTabletBanner="/assets/ABS_banner-tablet.png"
export var ABSDesktopBanner="/assets/ABSBanner.png"
export var LoadingIcon="/assets/loading.png"
export var GreedySalvationBanner="/assets/GSBanner.png"
export var ZINBanner="/assets/ZINBanner.png"